export const GLOBAL_CONFIG = {
  shouldAPICall: true,
  currencySymbol: import.meta.env.VITE_SHOPIFY_CURRENCY_SYMBOL,
  currencyCode: import.meta.env.VITE_SHOPIFY_CURRENCY_CODE,
  availableCurrencies: import.meta.env.VITE_SHOPIFY_AVAILABLE_CURRENCIES,
  settingMinPrice: import.meta.env.VITE_SHOPIFY_SETTING_MIN_PRICE,
  settingMaxPrice: import.meta.env.VITE_SHOPIFY_SETTING_MAX_PRICE,
  diamondMinPrice: import.meta.env.VITE_SHOPIFY_DIAMOND_MIN_PRICE,
  diamondMaxPrice: import.meta.env.VITE_SHOPIFY_DIAMOND_MAX_PRICE,
  priceKey: import.meta.env.VITE_SHOPIFY_PRICE_KEY,
  contactNumber: import.meta.env.VITE_SHOPIFY_CONTACT_NUMBER,
  emailId: import.meta.env.VITE_SHOPIFY_EMAIL_ID,
  diamondShippingDays: import.meta.env.VITE_SHOPIFY_DIAMOND_SHIPPING_DAYS,
  ringShippingDays: import.meta.env.VITE_SHOPIFY_RING_SHIPPING_DAYS,
  bannerImage: import.meta.env.VITE_SHOPIFY_BANNER_IMAGE,
  settingImage: import.meta.env.VITE_SHOPIFY_SETTING_IMAGE,
  diamondImage: import.meta.env.VITE_SHOPIFY_DIAMOND_IMAGE,
  ringImage: import.meta.env.VITE_SHOPIFY_RING_IMAGE,
  productCreateApi: import.meta.env.VITE_SHOPIFY_PRODUCT_CREATE_API,
  productFetchApi: import.meta.env.VITE_SHOPIFY_PRODUCT_FETCH_API,
  apiKey: import.meta.env.VITE_SHOPIFY_API_KEY,
  apiSecret: import.meta.env.VITE_SHOPIFY_API_SECRET,
  storeDomain: import.meta.env.VITE_SHOPIFY_STORE_DOMAIN,
  apiVersion: import.meta.env.VITE_SHOPIFY_API_VERSION,
  storefrontApiAccessToken: import.meta.env
    .VITE_SHOPIFY_STOREFRONT_API_ACCESS_TOKEN,
  adminApiAccessToken: import.meta.env.VITE_SHOPIFY_ADMIN_API_ACCESS_TOKEN,
  diamondDetailApiFunc: "diamondById",
};

export const ROUTES = {
  engagementRings: "/engagement-rings",
  engagementRingDetail: "/engagement-rings/products/:id",
  diamondType: "/:diamondType",
  shape: "/:shape",
  completeRingBuilder: "/complete-ring-builder",
};
